"""posts table

Revision ID: cad89ce76b07
Revises: d6ca3516c31a
Create Date: 2020-04-29 17:07:05.073936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad89ce76b07'
down_revision = 'd6ca3516c31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_breed', table_name='user')
    op.drop_index('ix_user_petname', table_name='user')
    op.drop_column('user', 'breed')
    op.drop_column('user', 'petname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('petname', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('breed', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_petname', 'user', ['petname'], unique=1)
    op.create_index('ix_user_breed', 'user', ['breed'], unique=1)
    # ### end Alembic commands ###
