"""users table

Revision ID: d6ca3516c31a
Revises: ece6b2541edc
Create Date: 2020-04-29 16:52:55.926449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ca3516c31a'
down_revision = 'ece6b2541edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('breed', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('petname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_breed'), 'user', ['breed'], unique=True)
    op.create_index(op.f('ix_user_petname'), 'user', ['petname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_petname'), table_name='user')
    op.drop_index(op.f('ix_user_breed'), table_name='user')
    op.drop_column('user', 'petname')
    op.drop_column('user', 'breed')
    # ### end Alembic commands ###
